
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Image image2;

	private global::Gtk.Button button4;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button button17;

	private global::Gtk.Button button15;

	private global::Gtk.Button button13;

	private global::Gtk.Button button6;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button3;

	private global::Gtk.Button button5;

	private global::Gtk.Button button7;

	private global::Gtk.Button button11;

	private global::Gtk.Button button2;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button button22;

	private global::Gtk.Label label1;

	private global::Gtk.Button button20;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("人眼判斷程式");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.image2 = new global::Gtk.Image();
		this.image2.WidthRequest = 160;
		this.image2.HeightRequest = 160;
		this.image2.Name = "image2";
		this.vbox1.Add(this.image2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image2]));
		w1.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.vbox1.Add(this.button4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button4]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button17 = new global::Gtk.Button();
		this.button17.CanFocus = true;
		this.button17.Name = "button17";
		this.button17.UseUnderline = true;
		this.button17.Label = global::Mono.Unix.Catalog.GetString("儲存\nSave");
		this.hbox3.Add(this.button17);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button17]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button15 = new global::Gtk.Button();
		this.button15.CanFocus = true;
		this.button15.Name = "button15";
		this.button15.UseUnderline = true;
		this.button15.Label = global::Mono.Unix.Catalog.GetString("開始\"人工判斷\"\nStart Hooman Recognize");
		this.hbox3.Add(this.button15);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button15]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("選擇資料夾\nSelect Folder\n(contains bar**.png)");
		this.hbox3.Add(this.button13);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button13]));
		w5.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("選擇原始圖片\nSelect Source Image\n(must 9:16 png)");
		this.hbox3.Add(this.button6);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button6]));
		w6.PackType = ((global::Gtk.PackType)(1));
		w6.Position = 3;
		w6.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w7.PackType = ((global::Gtk.PackType)(1));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("水(Water)");
		this.hbox1.Add(this.button1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
		w8.Position = 0;
		w8.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("火(Fire)");
		this.hbox1.Add(this.button3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button3]));
		w9.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("木(Leaf)");
		this.hbox1.Add(this.button5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button5]));
		w10.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("光(Light)");
		this.hbox1.Add(this.button7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button7]));
		w11.Position = 3;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("闇(Dark)");
		this.hbox1.Add(this.button11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button11]));
		w12.Position = 4;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("心(Heart)");
		this.hbox1.Add(this.button2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button2]));
		w13.PackType = ((global::Gtk.PackType)(1));
		w13.Position = 5;
		w13.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w14.PackType = ((global::Gtk.PackType)(1));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button22 = new global::Gtk.Button();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString("上一個(prev)");
		this.hbox5.Add(this.button22);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button22]));
		w15.Position = 0;
		w15.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("第？個");
		this.hbox5.Add(this.label1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label1]));
		w16.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.button20 = new global::Gtk.Button();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString("下一個(next)");
		this.hbox5.Add(this.button20);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.button20]));
		w17.Position = 2;
		w17.Fill = false;
		this.vbox1.Add(this.hbox5);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
		w18.PackType = ((global::Gtk.PackType)(1));
		w18.Position = 4;
		w18.Expand = false;
		w18.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 459;
		this.DefaultHeight = 349;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button22.Clicked += new global::System.EventHandler(this.OnButton22Clicked);
		this.button20.Clicked += new global::System.EventHandler(this.OnButton20Clicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button11.Clicked += new global::System.EventHandler(this.OnButton11Clicked);
		this.button2.Clicked += new global::System.EventHandler(this.OnButton2Clicked);
		this.button17.Clicked += new global::System.EventHandler(this.OnButton17Clicked);
		this.button15.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
		this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		this.button6.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
	}
}
